run_name: sonar_50k

# === Modèle ===
# model_name_or_path: facebook/nllb-200-distilled-600M
model_name_or_path: open_sonar/text/models/pretrained/nllb_1.3B
output_dir: checkpoints/sonar_50k
overwrite_output_dir: false


# === Données ===
source_lang: eng_Latn
target_lang: fra_Latn
train_file: datasets/nllb/*.parquet
validation_file: datasets/flores200/flores_200_dev_paired.parquet
test_file: datasets/flores200/flores_200_devtest_paired.parquet
overwrite_cache: false
dataset_streaming: true

# === Entraînement ===
do_train: true
per_device_train_batch_size: 32
per_device_eval_batch_size: 96
total_batch_size: 25000 # x 2 to have the real batch size
# gradient_accumulation_steps: 16
max_steps: 100000
save_steps: 1000
eval_delay: 2000
eval_steps: 1000
eval_strategy: steps
prediction_loss_only: true
load_best_model_at_end: true
metric_for_best_model: loss
greater_is_better: false
disable_tqdm: false
max_source_length: 256
max_target_length: 256
gradient_checkpointing: false

ddp_find_unused_parameters: false
logging_steps: 100
save_total_limit: 5
shuffle_buffer_size: 1000

dataloader_num_workers: 0
dataloader_drop_last: false
dataloader_pin_memory : true


learning_rate: 8.e-4
lr_scheduler_type: inverse_sqrt
warmup_steps: 8000
max_grad_norm: 1.0
weight_decay: 0.005
adam_beta1: 0.9
adam_beta2: 0.98
adam_epsilon: 1.e-6

mse_ratio: 0.2
dae_ratio: 0.02

bf16: false
fp16: true

accelerator_config:
  split_batches: false
  dispatch_batches: false
  even_batches: true
  use_seedable_sampler: true
  non_blocking: false
